language: java

jdk:
  - oraclejdk8

#dist: precise
dist: trusty
sudo: false

env:
  - NODE_VERSION=v8
  - NODE_VERSION=v7
  - NODE_VERSION=v6
  - NODE_VERSION=v5
  - NODE_VERSION=v4

cache:
  yarn: true
  directories:
  - $HOME/.m2

install:
  - nvm install $NODE_VERSION
  - npm install
#  - wget https://yarnpkg.com/install.sh
#  - chmod 755 install.sh
#  - ./install.sh
#  - $HOME/.yarn/bin/yarn

script:
  - if [[ "${NODE_VERSION}" == 'v8' ]]; then npm run codecov; else npm run test; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/caa35ceb4dd217d50b26
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
